package pl.karas.cyclingmanagementsystem.model;

public enum ERole {
    ROLE_ADMIN,
    ROLE_MODERATOR,
    ROLE_USER,
    ROLE_COACH_ZAK,
    ROLE_COACH_ZAKINI,
    ROLE_COACH_MLODZIK,
    ROLE_COACH_MLODICZKA,
    ROLE_COACH_JUNIOR_ML,
    ROLE_COACH_JUNIORKA_ML,
    ROLE_COACH_JUNIOR,
    ROLE_COACH_JUNIORKA,
    ROLE_COACH_ORLIK,
    ROLE_COACH_ORLICZKA,
    ROLE_COACH_ELITA_M,
    ROLE_COACH_ELITA_K
}
